### ISSUE TITLE
Redirecting development to git-ssb

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-server#369]
On the [ssbc](http://github.com/ssbc/) call yesterday we talked about using git-ssb as our primary development platform, and using Github as a secondary backup -- such as when we need a feature that is not available on git-ssb. The hope is by focusing our development on our own tool, we will improve it until it's better than Github, with the added benefit of being distributed.

To see Scuttlebot issues on git-ssb on the public web, navigate to: http://git.scuttlebot.io/%25M0TrM%2BoJT2i%2FphUJO%2FfZ2wkK2AN2FB1xK0tqR7SNj58%3D.sha256

If you are unable to leave an issue on git-ssb using either [Patchbay](http://github.com/ssbc/patchbay) or [git-ssb-web](https://github.com/clehner/git-ssb-web), feel free to leave it here on Github.

**Comment by dominictarr** [comment]
we need an ad for git-ssb and links to the gateway in the readme, so that readers of the github can see the address.

**Comment by dominictarr** [comment]
oh, maybe we can put that in the github issue template, then when someone creates a issue or PR, they are reminded to use git-ssb

**Comment by evbogue** [comment]
This issue is still as relevant as ever, now that Github is owned by Microsoft. Nice try stalebot.

**Comment by evbogue** [comment]
I believe this issue is still relevant to the ssb community, considering that we have `git-ssb` and it is an innovative alternative to Microsoft Github: 

http://decent.evbogue.com/#%UbmyE84JJMc7TkS7gdDW3nnRC4+K69xfTl/CV45B0sA=.sha256
