### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by internalfx** [ssbc/ssb-server#467]
My pub keeps crashing after about 10 minutes

![image](https://user-images.githubusercontent.com/583701/35649674-101e2dc2-0697-11e8-86c3-b0f56bd5ac50.png)

**Comment by internalfx** [comment]
I'm also seeing several `server error Error: wrong number` errors

**Comment by arj03** [comment]
I recently fixed a memory leak in a module used by scuttlebot. Could you try reinstalling scuttlebot and see if that helps? You should have level-post 1.0.7 to have the fix.

Thanks

**Comment by optikfluffel** [comment]
@internalfx Same here.
@arj03 Maybe that's because there's still a lot of `"level-post": "1.0.5"` in [package-lock.json](https://github.com/ssbc/scuttlebot/blob/master/package-lock.json). Or does npm handle this and only uses the newest version when there are multiple in parallel?

**Comment by arj03** [comment]
Hmm yeah the package-lock.json must die or at least be kept strictly up2date. You can do a local npm ls to see which versions you have. npm outdated is pretty nice as well.

**Comment by optikfluffel** [comment]
Mmh, seems to be "fine":

    npm ls -g | grep level-post
      | | +-- level-post@1.0.7 deduped
      | +-- level-post@1.0.7
      | | +-- level-post@1.0.7 deduped

**Comment by arcfide** [comment]
I'm seeing a tone of these wrong number errors almost constantly (about one every half a second to 1 second) and I can't seem to keep my pub running for longer than about 4 - 5 minutes.

**Comment by arcfide** [comment]
Is this considered fixed?

**Comment by christianbundy** [comment]
Hard to say, I don't think we've ever been able to successfully reproduce the memory leak. Can you reproduce the issue locally?

I'm not sure whether the "wrong number" error is related, but if you're having that issue *without* a memory leak then I'd recommend creating an issue so we can get to the bottom of it.

**Comment by arcfide** [comment]
Last time I checked, the memory leak was rampant, consistent, and happened pretty much all the time for my installation.

**Comment by christianbundy** [comment]
Would you mind checking again with the latest version? I ran `sbot server` for just under ten minutes while making some curry fried rice and it doesn't look like my memory usage is increasing over time:

![process-screenshot](https://user-images.githubusercontent.com/537700/50198291-d251c100-02ff-11e9-83d6-193df9319ca6.png)

**Comment by cryptix** [comment]
@christianbundy:  Is this on a remote machine getting dialed by the rest of the network? I can attest that our pub uses a lot of ram still...

**Comment by christianbundy** [comment]
No, that's my desktop. My pub *also* uses a lot of memory, but the ssb-server process usually hovers between 15% and 25% memory usage on my Raspberry Pi 3B (which is a lightly used pub). Do you have a memory leak on your device, or just a lot of RAM usage?

**Comment by arcfide** [comment]
How much memory do you expect it to use?

**Comment by christianbundy** [comment]
I'm sure it depends on the server load, but on average I'm personally experiencing between ~150 MB and ~250 MB of memory usage. I've also experienced intermittent crashes, so I run my pub with:

```sh
while true; timeout 1h npm start; done
```

With that said, I don't have any information that would help me diagnose the problem as a memory *leak*. I'd really like to help you if you're having a memory leak, but the only data point I have is the initial screenshot from January.
