### ISSUE TITLE
Pubs should have option to enforce gossiping only with peers they know

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-server#491]
From [%Wou59mdQR37z0qDUDZMpAzvS/NdnZrqT5iC9SHYzOAA=.sha256](https://viewer.scuttlebot.io/%25Wou59mdQR37z0qDUDZMpAzvS%2FNdnZrqT5iC9SHYzOAA%3D.sha256):

> ## :globe_with_meridians::closed_lock_with_key: Pubs could enforce gossiping only with peers that are `n` hops from someone they already follow 
>
> Right now (afaik), pubs will gossip with anyone that knows their public key. This currently allows anyone that knows a pub's address and key to start spidering the network from that point. They can request the pubs feed, which gives them a list of everyone the pub follows. Then they can request those feeds, and so on. Then they learn about other pubs, and get more feeds etc etc.
>
> However, if pubs checked to make sure that the remote peer was actually a friend or a foaf, then this would make spidering impossible! You'd have to actually get people to follow you first! ooo could still be available to everyone, but getHistoryStream should only be available to people on the pubs hops graph.

**Comment by cryptix** [comment]
I'm really confused. I thought this is what the hops distance is all about.

I assumed when peers are not following each other (in that distance) the connection would not be accepted at the secret-handshake level.

**Comment by mmckegg** [comment]
@cryptix 

>  I thought this is what the hops distance is all about.

The hops distance is from the pulling end. It is how many layers deep to request from your follow list. It is not enforced by the other party.

My understanding is that peers will accept connections from anyone that:

a) knows the ip, and
b) know the public key

At this point it is then possible to request their feed. This gives you a list of everyone they follow. You can then use this list to request the feeds of everyone the pub follows, and so on.

But since you must disclose your own public key to connect (and we already check this for blocked feeds), it should be fairly straight forward to add enforcement of the hops distance at the gossip level.

**Comment by dominictarr** [comment]
yup definitely. currently yes it's just random, from back when that seemed like enough, and we havn't gotten around to fixing that @pietgeursen is doing a ssb-mobile quest on gossip strategy, I'm gonna do a call with him about this later today

**Comment by arj03** [comment]
There is now https://github.com/ssbc/ssb-incoming-guard that takes care of the incoming part.

**Comment by staltz** [comment]
Don't do that, Mr. Bot, this issue is still relevant.

**Comment by staltz** [comment]
Bot, shut up. (I won't be polite to robots, sorry)

The plan with this issue is related to the gossip rewrite: https://hackmd.io/e0c85WFhRYWeA4wSnaCkyg?view#

**Comment by arj03** [comment]
Also relevant [ssb-friend-pub](https://github.com/ssbc/ssb-friend-pub)
