### ISSUE TITLE
plugins.install silently fails if sbot is running via patch*

### ISSUE THREAD

**Issue by rabble** [ssbc/ssb-server#505]
I haven't figured out why this is happening, but it feels like a bug. If you run sbot server from the command line then the plugins.install commands work. But if you've opened up one of the electron apps like patchwork and then try and use the 'sbot plugins.install' command it silently fails and just returns the help message for sbot. If it can't work when sbot is envoked when it's run from electron it should say something as an error.

**Comment by cryptix** [comment]
Sorry you ran into this. Patchworks [internal sbot](https://github.com/ssbc/patchwork/blob/a9fe8868dd71da9e2f16834cdf26233521d56798/server-process.js#L7) currently does not expose the commands for managing plugins ([here](https://github.com/ssbc/scuttlebot/blob/0487bdcc9476f84c5edb8eff3d45ea0e479f7e0d/bin.js#L42) they are in standalone).

See ssbc/patchwork#610 and ssbc/patchwork#686 for more discussions on this.

More important is the work on overhauling the plugin architecture for cross-implementations. The discisson can be found under [%oxtXLx0AdZgcQpLlLYjDfrgzMJw1j8zv0YSwEtFAep8=.sha256](http://viewer.scuttlebot.io/%25oxtXLx0AdZgcQpLlLYjDfrgzMJw1j8zv0YSwEtFAep8%3D.sha256). Once this work is done, we are on good footing for applications to register the plugins they need to function.
