### ISSUE TITLE
Standard schema for mutable messages

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-server#506]
![2018-05-25-174403_1330x655_scrot](https://user-images.githubusercontent.com/2468866/40568924-4d691a06-6043-11e8-9126-715189ddbe47.png)

As we've discussed on the main ssb network, I've been working on a prototype of mutable messages for Decent for the past month. 

The repo is here: https://github.com/evbogue/mvd 

Try the testnet here: http://mutable.evbogue.com/

`mvd` is getting _very_ close to being ready for production. Once it has all of the features of `minbase` I'm planning on using `mvd` as the main client in Decent. 

Before I push `mvd` into production on the Decent altnet, I want to take the time to discuss what the standard message schema should be for mutable messages. What I want is forward compatibility with mutable messages when they are implemented in other clients and eventually used on the main network.

@dominictarr said he'd prefer that we include the `root` of a thread, and then use `branch` http://viewer.scuttlebot.io/%25CwR0yPElbSYV5qBRLBwXoRHe7ccFz/7Iz0KweBnvOX4=.sha256

Right now I am using:

```
type: 'update',
original: 'points back to first, unedited message',
updated: 'points to the latest message in a sequence of messages',
```
I will include the root thread. 

In regards to `branch`, should that post to the latest edit, or the original message in a sequence of edits?

The linked thread above also mentions including `diffs`. Do we want to include diffs?

All of these changes are easy, as long as we agree on our schema now. Once we start using mutable messages in production it will be more difficult to change the schema.

What do the @ssbc/members think about what the schema for mutable messages should be on ssb?

**Comment by pietgeursen** [comment]
Hey @evbogue,

I'm about to go to a family thing so I haven't engaged with all of this.
Just saw this:

> All of these changes are easy, as long as we agree on our schema now.
Once we start using mutable messages in production it will be more
difficult to change the schema.

And it made me think of the work we've been doing on ssb-poll-schema
<https://github.com/ssbc/ssb-poll-schema>
The design of it gives a way to define how to parse different shaped
messages into a standard message shape that you can rely on. And hopefully
a way to manage versioning schema too.
So, you don't have to get consensus on what the perfect implementation is,
you could just build something that uses this pattern. Maybe? Sorry got to
run!

Excited for this feature though, great work!

**Comment by dominictarr** [comment]
@evbogue the most important thing, is that sometimes branch needs to point to multiple messages. normally, the branch is the latest message. But it's only the latest message _you have seen_. So if alice posts message A1 and then bob and charles both respond while offline,  B1(->A1) and C1(->A1), then the latest message they see is A1. lets say that B1 was actually created an hour before C1, but charles didn't know about it. Now, receives both messages and replies, and the branch is  both B1 and C1. A2(->[B1,C1])

In an alternative dimention where C did know about B1, their message would have been C1(->B1) and A2(->C1)

---

Also, I recommend you include the root of the thread on the update message - then it will be fast to retrive all messages for a given thread in a single database query.

**Comment by evbogue** [comment]
@pietgeursen I've cloned down https://github.com/ssbc/ssb-poll-schema and I'm going to take a look at it later tonight!

@dominictarr I'm going to include the root of the thread. Right now I'm doing an individual query against each message, and it'd be much more effective to grab the entire thread at once and then render it. 

Since my implementation only allows the author to edit their own posts, I don't think we'll need to specify two branches. If we decide to implement multi-editor mutable messages we might need more branches.

BUT, I am not doing including multiple branches with how I've implemented replies. So, I need to make sure I'm specifying more than one branch when they are present. I'll take a look at Patchless and make sure I'm implementing a similar pattern.

I think the schema will work:

```
type: 'edit',
root: 'root of thread, or original message if it doesn't have a root',
branch: 'last edit, or original message edited',
original: 'original message edited' 
```

**Comment by dominictarr** [comment]
@evbogue okay yes if only the original author is allowed then it would be okay to not support branch. (however, what about same-as?)

I'd also suggest using branch regards the thread (not just root) as this will enable later messages to branch from the edits, which will mean OOO can see the edits too. This means the edits will be fully a part of the thread.

**Comment by dominictarr** [comment]
(i just didn't mention that in my previous post because branch can be confusing and it was a lot of information to load in there)

**Comment by evbogue** [comment]
@dominictarr yah, I'm a little confused about branch in regards how it'd work with edits. 

I wonder if it'd be better to leave branch for replies, and use a different field name for edit backlinks? 

Right now my implementation has a query looking for messages with `type: 'edit'` and `original: msg.key`, then I replace the message with the edits as they `pull.drain` in. Edits also link to the previous message edit with `branch` and `updated` -- which represent the same exact thing right now, but aren't used for queries yet.

But now it gets confusing as to whether reply should branch from the original message key or the edited message key!

Regardless this works right now, so feel free to try it out on the testnet here: http://mutable.evbogue.com/

The relevent code here: https://github.com/evbogue/mvd/blob/master/render.js#L37-L50

**Comment by mixmix** [comment]
Re branch, use the "heads" function from ssb-sort to do the heavy lifting
for you.

The branch field isn't about human readabilty so much as supporting the
casual ordering and messaging it possible to reason about order and context
in which things like edits happened. There's a nice method on ssb-sort
called "missingContext" which helps with this too. We're gonna use this in
ssb-poll stuff to reveal which votes were said without the context of some
other votes.

**Comment by dominictarr** [comment]
> I wonder if it'd be better to leave branch for replies, and use a different field name for edit backlinks?
a different field name is a good idea. Oh, if you had thread level `branch`ing (as mix describes, to keep track of who did what in what context) then you could get away with just a link to the `original` message edited (since that would still express order through previous edits via the thread `branch`)

side note: we've also discussed giving likes in a thread a `root` and a `branch`.

**Comment by evbogue** [comment]
@dominictarr That makes sense -- I tried using `ssb-backlinks` for votes last night, and it started thrashing my browser window fairly quickly.

I've been a little busy this week, so I haven't been able to look into how to use `ssb-sort` to do the heavy lifting here. 

What's the easiest way to have `ssb-sort` assign a branch to a vote message? (I'll answer this question myself in a bit, if it's not immediately answerable off the top of anyone's head.) Then I'll go ahead and use it to assign branches to edits while I'm at it.

**Comment by mixmix** [comment]
same as you'd do for anything - you just give it an array with a bunch of
messages that represent the current context. It will sort them and tell you
which are the heads. It will give you back a single one or an array.

e.g. sort.heads([msgA, msgA, msgB, msgC1 msgC2])  =>  [msgC1, msgC2]

**Comment by keks** [comment]
Awesome, great work! Just to be clear, for now we're "only" (as if that wasn't enough) about edits to messages of type `post`, right?

**Comment by mixmix** [comment]
I think branch is still really useful for edits - you want to be able to see when it happened and in what context

**Comment by evbogue** [comment]
@keks correct, these messages are edits to the message type `post`

@mixmix Yup, I'm going to generate the branch field and include it within edit messages when they are published.

**Comment by regular** [comment]
Only seeing this now. I've implemented mutable messages and indexes for mutable messages in [ssb-revisions](https://github.com/regular/ssb-revisions)

Also see #ssb-revisions on ssb.

**Comment by evbogue** [comment]
@regular Cool, I didn't know you were also working on mutable messages.

From a quick read, I think we took slightly different approaches. I wonder how different we are, and whether we can bring these together into a similar approach?

I have mutable messages and `ssb-wiki` implemented in http://github.com/evbogue/mvd 

Here's the mutable messages dev diary from the Dfinity grant: http://gitmx.com/#%PtxLfewN03z3NJ0b+oBDeigt0z5IWTQIYoKyUB5/8VQ=.sha256

I'd really love to bring mutable messages to Patchwork -- as that's the client most people use. I've been watching @mmckegg 's Patchwork debloat, and I think once the dust has settled it'll be a good time to think about how to bring mutable messages to Patchwork.

**Comment by christianbundy** [comment]
@regular @evbogue 

Has there been any progress on consolidating the two schemas for mutable messages? No rush, just wanted to check in since I'm interested in this and hadn't heard anything.

**Comment by regular** [comment]
@christianbundy @evbogue , I wanted to see how using ssb-revisions feels when being used in real-world projects. I'm making heavy use of it now in two projects and I am happy with it, no problems thus far. I will write about it on ssb once "tre" (successor of ssb-cms) is more mature and people can check it out with more ease.

**Comment by evbogue** [comment]
@christianbundy @regular Not yet, but we should set aside some time to discuss the differences. 

I'm using `type: edit` and `updated: msg_id` to link back to the message. Then there are root and branch fields.

**Comment by regular** [comment]
My stuff is documented here: https://github.com/regular/ssb-revisions

**Comment by regular** [comment]
@christianbundy It's not quite as simple as that, I'm afraid. You'll need indexing to make it efficient, it's all in the docs I linked to above. Plus, I'd really like to try this out in a separate network before experimenting in the main network, hammering existing clients with messages they can't handle. I am in the process of doing just that. ssb-revisions already is an sbot plugin, btw, clients can use it directly.

**Comment by christianbundy** [comment]
Would that require plugins to specifically use the view when looking up messages? My thought above was to use [a map function in flumedb](https://github.com/ssbc/ssb-db#ssbdbaddmap-fn), which works the same way that the private message decryption works (i.e. before flumedb views even see it). That way you'd just need to include the plugin and mutable messages would *just work*, without client developers needing to spend any time on integration.

The only downside is that we'd need to [regenerate views](https://github.com/flumedb/flumedb/issues/23) when new messages come in, and it's performance-intensive to regenerate every view for every message when *really* we'd only want to modify one message.

**Comment by regular** [comment]
@christianbundy hmmm ... interesting. But that would be very static, too static I'd say. In my clients I even need realtime updates when a message is edited, like in instant messaging clients. I am using [tre-watch-heads](https://github.com/regular/tre-watch-heads/blob/master/index.js) (work in progress). It gives you a mutant-compatible observable for a message. Because re-generating views would be way to expensive, but you still need indexing, I created ssb-review-level and ssb-review-reduce, they index the latest head of mutated messages. These views are fed by a special update stream created by ssb-revisions.

I think clients have to be very aware of mutable messages. Ideally, it's a subjective choice whose edits you as a user want to see. You may want to allow edits by other people then the author, you may want to specify a group of users that are allowed to edit messages you author, etc. Also, clients need to be aware of mutable messages to be able to publish edits and they should be able o display whether a message was edited and when and display the entire message history. Without these features, there would be a lack of transparency and it would probably be a more confusing user experience.

**Comment by evbogue** [comment]
@regular In `mvd` I'm able to achieve real time updates to the messages by using `ssb-query` against the type of `edit` and then setting `live: true`. Then I do some dom manipulation in hyperscript to replace the message element with the new data. I also render an "Edited by user_id" to the render so that you can see that it has been updated. 

See: https://github.com/evbogue/mvd/blob/master/render.js#L179-L195

This is slower than just rendering a message without checking for updates, but it's no slower than checking for Votes against a message and rendering Stars on the message -- which I also do. 

The indexes are already generated using `ssb-query`, because I'm querying against the type for messages that link back to the message. 

There are probably plenty of different strategies to get these messages, but if we can agree on schema for publishing the messages, we'll at least be posting the same types of messages.

**Comment by regular** [comment]
@evbogue yes, I understood, I was arguing against implementing mutable messages in the way @christianbundy described, because that would be too static (also: edits typically come in after the original message, so that wouldn't work, I think)

ev, I am not planning to use ssb-revisions on the main network anytime soon, it is for my CMS-like clients, so it serves my specific purposes, so I don't feel the urge to standardise, especially not before having gained lots of experience by using it for a while on isolated networks. Having said that, I am using the revisionRoot/revisionBranch approach for a year now, and I am still happy with it. Your solution wouldn't work for me. I'd be interested to hear if there's something you dislike about ssb-revisions though, if it would work for your use case.

**Comment by evbogue** [comment]
This is still relevant. But, since I can't seem to get consensus or an executive decision on what schema to use, I just continue to use my own. Visit: http://decent.evbogue.com/#%PtxLfewN03z3NJ0b+oBDeigt0z5IWTQIYoKyUB5/8VQ=.sha256 for more details
