### ISSUE TITLE
Sbot getting stopped with 200 servers

### ISSUE THREAD

**Issue by devashish-laitkor** [ssbc/ssb-server#514]
Hi,
 We are trying to setup 200 servers with scuttlebutt, we have also successfully configured it. 
But now we are facing issue with it.

When we send transaction or send a command Sbot server are getting stopped, randomly, Did not find any error in the logs. 
Please check screenshot for the same 
Sbot on all server running
http://nimb.ws/nxkqVL
After 1-2 minutes we found one Sbot gets stopped
http://nimb.ws/OUkVxL
After 2-3 minutes some more Sbot server gets stopped
http://nimb.ws/FGeP6L
And this happens for other Sbot servers 
http://nimb.ws/n0AFaY
http://nimb.ws/BDjptc
 We also want to mention that it was working fine till we have configured 40 servers with it.
Any help will be appreciated.

We are getting following error message.

"error":"Error: challenge not accepted\n    at abort (/dir/messagenode/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/dir/messagenode/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/dir/messagenode/node_modules/pull-reader/index.js:42:23)\n    at /dir/messagenode/node_modules/pull-reader/index.js:59:18\n    at /dir/messagenode/node_modules/pull-reader/index.js:20:7\n    at /dir/messagenode/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/dir/messagenode/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/dir/messagenode/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)"}

Thanks

**Comment by christianbundy** [comment]
Thanks for opening this issue. Could you explain more about your setup, or share code to simulate/reproduce this environment? I'd love to help debug but I'm unsure where to start.
