### ISSUE TITLE
Investigate using mdns for advertisements?

### ISSUE THREAD

**Issue by jedahan** [ssbc/ssb-server#524]
So libdweb is pretty dang neat - chances are, we will have mDNS service discovery in the browser very soon. Since there are now a decent number of web clients for scuttlebot, what are people's thoughts on mDNS advertisements for `ssb-ws` or other remote protocols? How does this fit into / break the philosophy of ssb?

Example untested code a client could use to find a local bot:

```js
const muxrpcServices = await browser.ServiceDiscovery.discover({
  subtype: "ssb",
  type: "ws",
  protocol: "udp"
})
```

related: https://github.com/evbogue/mvd/issues/5

**Comment by dominictarr** [comment]
I would happily merge a PR to add MDNS advertisements. the only reason we didn't do it in the first place was because there wasn't a good mdns library available at the time. there were a couple of wonky-looking native bindings, but these are usually more trouble than they are worth in node (although the support for binary addons has improved since then)

I see this: https://www.npmjs.com/package/mdns-js but sounds like it's not quite ready, or maybe just doesn't have every feature.

**Comment by jedahan** [comment]
The most up-to-date forks of mdns-js I've used are https://github.com/ardean/spread-the-word (typescript, slightly nicer api), and https://github.com/taoyuan/nbonjour . One of the tricky parts of a pure-js mdns service is that it wont work if there is already a native process listening, but these have worked both on my mac and on raspberry pis. Glad to see you are open to at the very least a plugin PR.

**Comment by jedahan** [comment]
For inspiration, something like: https://www.npmjs.com/package/libp2p-mdns would be a good template for a plugin

**Comment by christianbundy** [comment]
I'd love to see this merged. I've only skimmed the [readme](https://github.com/mdns-js/node-mdns-js/blob/master/README.md), but it looks like this is [obviously] not something that will work in the browser, so maybe this would be best implemented as a plugin?

**Comment by jedahan** [comment]
This is still relevant. It may be best as a plugin, if the plugin has access to the same information needed for advertisements.
The best things to do would be:
Figure out what needs to be send as advertisements.
Figure out if a plugin has access to what it needs.
Determine the best package
- [ ] libp2p-mdns
- [ ] spread-the-word
- [ ] nbonjour

**Comment by christianbundy** [comment]
I've been super excited about the discovery-swarm module lately, maybe we could use whatever they're using?
