### ISSUE TITLE
sbot creates invalid invites.

### ISSUE THREAD

**Issue by campydirt** [ssbc/ssb-server#526]
sysinfo: OS: Windows 2012 R2

Using "sbot invite.create 1" create an invalid invite code.
As a proper invite key should be: <host>:<port>:<ID>~<code>
Creating an invite creates something similar to this: :<port>:~<code> missing hostname and it's id.

In the image, yes it does say to create 1000 invites (Big community) anywho, this error happens with any amout of invites created... not just 1 or 1000.
![test](https://user-images.githubusercontent.com/33609627/44550977-c4928300-a6f3-11e8-89e6-b374e9b0b4f5.PNG)

Steps to reproduce:
~Setup Win2012R2 host
~Install Node JS
~npm install scuttlebot
~sbot server --host <host> --port <port>
~sbot invite.create 1

**Comment by christianbundy** [comment]
> sysinfo: OS: Windows 2012 R2
>
> Using `sbot invite.create 1` create an invalid invite code.  
> As a proper invite key should be: `<host>:<port>:<ID>~<code>`  
> Creating an invite creates something similar to this: `<port>:~<code>` missing hostname and it's id.  
>
> In the image, yes it does say to create 1000 invites (Big community) anywho, this error happens with any amout of invites created... not just 1 or 1000.
>
>![test](https://user-images.githubusercontent.com/33609627/44550977-c4928300-a6f3-11e8-89e6-b374e9b0b4f5.PNG)
>
> Steps to reproduce:
>- Setup Win2012R2 host
>- Install Node JS
>- `npm install scuttlebot`
>- `sbot server --host <host> --port <port>`
>- `sbot invite.create 1`

Hey @campydirt! Sorry to hear you're having issues with those invite codes. I'd love some more information on which Node version you're using, plus the output of `sbot getAddress` if you can. For example, here's what it looks like for me:

```console
$ sbot getAddress
"net:192.168.0.109:8008~shs:+oaWWDs8g73EZFUMfW37R/ULtFEjwKN/DczvdYihjbU="
```

I'm not sure whether it matters, but if you *can* I'd love to see your hostname in case you're using something I'm unfamiliar with. Based on your screenshot it looks like your port number is 8008, but please correct me if I'm wrong. Thanks!

**Comment by christianbundy** [comment]
By the way, this *may* be related to https://github.com/ssbc/scuttlebot/issues/390 and/or https://github.com/ssbc/scuttlebot/issues/496.

**Comment by campydirt** [comment]
So, yes, port is 8008, thought that was the default port...
My node version is 8.9.4, NPM version is 5.6.0

When using "sbot getAddress" It returned an error: "unexpected end of parent stream"

**Comment by campydirt** [comment]
On a side note of all of this, made the valid invite code, and it says that I cant connect to the pub. But on the left side of Patchwork under (Connected pubs) You'll see my pub is connected just fine and is online...

**Comment by staltz** [comment]
Can you install multiserver@1.13.3 and retry in sbot?

**Comment by campydirt** [comment]
npm i multiserver? Or is it software?
If its npm, I installed it and sbot invite.create 1 did the same thing.

**Comment by campydirt** [comment]
I can confirm that both modules are installed globally.

**Comment by derekchiang** [comment]
I can confirm that I'm running into this problem on ubuntu 18.04 as well.  I'm running it locally and `npm i -g multiserver` does not help.

**Comment by christianbundy** [comment]
@derekchiang Just to clarify, are you having an issue with creating an invite code or with `sbot getAddress` too?
