### ISSUE TITLE
Server has no public ip address

### ISSUE THREAD

**Issue by derekchiang** [ssbc/ssb-server#540]
As of `sbot 12.0.0` I'm gettting the `Server has no public ip address` error when I do `sbot invite.create`.  I'm still launching the sbot server with the `--host IP` flag.  Did the flag change or something?

**Comment by derekchiang** [comment]
Most likely related to https://github.com/ssbc/scuttlebot/issues/541

**Comment by arj03** [comment]
In this version one can have multiple connections, so to create an invitation, you need to have a config sections that tells sbot what the external host is. See this: https://github.com/ssbc/ssb-config#connections.

**Comment by arj03** [comment]
@derekchiang can you try 12.0.1? See notes here:

https://github.com/ssbc/scuttlebot/releases/tag/12.0.1

Thanks for reporting!
