### ISSUE TITLE
--path doesn't change the config location?

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-server#559]
should `sbot server --path /to/my/altssb` pick up $HOME/.ssb/config?

this makes my tests fail because it tries to load a plugin from that config in the alt location...

here is part of my log, trying PR #557 
```
...
ok 6 sbot exit code should be zero
# sbot should have websockets and http server by default
scuttlebot 13.0.0 /tmp/1539777000392 logging.level:notice
my key ID: iM0N6BODZlKWK6GaveTyTJHMluEl4FLHp8GssRnoVyo=.ed25519
module.js:549
    throw err;
    ^

Error: Cannot find module '/tmp/1539777000392/node_modules/ssb-npm-registry'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.module.exports.loadUserPlugins (/home/cryptix/ssb/scuttlebot/plugins/plugins.js:185:20)
    at Object.<anonymous> (/home/cryptix/ssb/scuttlebot/bin.js:59:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
not ok 7 sbot exit code should be zero
```

ps: there is no `config` file in ` /tmp/1539777000392`

**Comment by cryptix** [comment]
on ssb: `%6ntnWCGx+OIo/bZpuQ8Ic4OGVsW+GKz8mEaDpAktB7k=.sha256`

**Comment by cryptix** [comment]
moving my `.ssb` away makes them pass.. sooo....

**Comment by regular** [comment]
If you set the current working directory to one that contains a file called `.ssbrc`, it will be picked up by sbot. Have a look at https://www.npmjs.com/package/rc#standards

**Comment by cryptix** [comment]
> So, yes, your working directory is wrong. 

okay I get that for ssb-integration-tests but I'm using #557 here. Are you proposing `cd`ing into the tmp path and creating a .ssbrc there?

**Comment by regular** [comment]
Oh! That's my fault. i was testing on a machine without `~/.ssb/config`, so it was fine for me. Let me fix that and push.

**Comment by regular** [comment]
Pushed.

**Comment by cryptix** [comment]
nice! i'd have done the same (adding env to the exec calls)

**Comment by christianbundy** [comment]
I want to make sure stale[bot] isn't being silly -- is this issue still a thing, or good to close?
