### ISSUE TITLE
Listening on undefined:8008 (multiserver net plugin)

### ISSUE THREAD

**Issue by evbogue** [ssbc/ssb-server#578]
When I start scuttlebot@13.2.0 I see this below, and `mvd` doesn't seem to work with scuttlebot anymore. I'm not sure if the two are related? 

```
Listening on undefined:8008 (multiserver net plugin)
Listening on :8989 (multiserver ws plugin)
```

I ended up hardcoding mvd to scuttlebot@13.0.3 until the black friday mayhem is over at work, as I haven't had time to investigate.

**Comment by cryptix** [comment]
I started seeing a similar problem ( https://github.com/ssbc/scuttlebot/pull/566#issuecomment-447834469 ). The only fix I have right now is to override host to `0.0.0.0` through config but we really need to fix the default case..!
