### ISSUE TITLE
add npm-shrinkwrap.json, deprecate scuttlebot-release

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/ssb-server#595]
this issue is to discuss the changes proposed in https://github.com/ssbc/scuttlebot/pull/575#issuecomment-439460397

> I've just pushed a change that moves `npm-shrinkwrap.json` from the `scuttlebot-release` module into this readme, which I propose we use. The differences between the different types of lockfiles:
>
> - [`package-lock.json`](https://docs.npmjs.com/files/package-lock.json): lockfile for libraries (click the link for more details)
> - [`npm-shrinkwrap.json`](https://docs.npmjs.com/files/shrinkwrap.json): the above *plus* it's published to NPM and respected when you run `npm install -g ssb-server`, great for applications
>
> Once this PR is merged I propose that we deprecate the `scuttlebot-release` package and archive the GitHub repository. This gives us the benefits of having a lockfile (:tada:) without the hassle of maintaining two repos and modules for the same software.

see also `%RZW7keS4V1Fv4AvUaVvdo7A4hgtLZOdoKDWXByALdE8=.sha256`

**Comment by ahdinosaur** [comment]
i'm pretty keen for us to shrinkwrap directly in `scuttlebot` / `ssb-server`, as having a separate module creates an inconvenience for anyone using `scuttlebot` / `ssb-server`. i'm not sure i understand why we wouldn't want our master branch here to also be our shrinkwrapped release.

i was extra motivated to create this issue because learned that it's not enough to search & replace every mention of `scuttlebot` for `scuttlebot-release`:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'scuttlebot-release/plugins/master'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at startServer (/home/dinosaur/repos/peachcloud/peach-ssb-server-js/index.js:11:10)
    at Object.<anonymous> (/home/dinosaur/repos/peachcloud/peach-ssb-server-js/bin.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

so i'm curious, what are the arguments in favor of having a separate repo and module for shrinkwrapped releases? /cc @dominictarr

**Comment by dominictarr** [comment]
btw, that comment of @christianbundy is the wrong way around. shrinkwrap is for libraries. that means that your dependants are bound to your shrinkwrap, which package-lock doesn't do. package-lock only makes sense for things that are push deployed with git or built into a binary. package-lock doesn't gain anything for ssb-server except that it could cause errors where the locked version passes the tests but not if you freshly install.

I think shrinkwrap is a great idea, but I think npm's shrinkwrap is wonky and poorly documented and has unclear behaviour and is annoying, when linking in other deps for testsing and dev. So a separate repo was mainly the way to avoid all the problems with it.

also, while we are talking about shifting everything around, this is also relavant: https://github.com/ssbc/ssb-server/issues/602

**Comment by christianbundy** [comment]
> package-lock only makes sense for things that are push deployed with git or built into a binary. > package-lock doesn't gain anything for ssb-server except that it could cause errors where the locked version passes the tests but not if you freshly install.

Lockfiles aren't only used for deployment and releases, they make it easier for everyone working on the module to use the same dependency tree so we can avoid ["works on my machine"](https://github.com/ssbc/ssb-server/issues/576#issuecomment-441136846) headaches. Plus, they act as a known-working dependency tree for each dep change, which makes debugging deep dependencies much easier.

I agree that it can be confusing, but I don't think we should pretend that it's so black and white.

**Comment by dominictarr** [comment]
@christianbundy if we make the refactor suggested in this thread: https://github.com/ssbc/ssb-server/issues/602 so that all the _code_ is moved out of ssb-server, so that it's just a bundle of plugins, then I'd be all for a shrinkwrap. (I'd like the emphasize that being able to run the tests for the whole bundle is essential, we want to be _more_ sure things arn't gonna be breaking)
