### ISSUE TITLE
add ssb-ooo to default plugins

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-server#600]
Is anything currently blocking this from happening?

I believe it is already included in scuttle-shell, but it's not much use including it in clients until a good few pubs have it!

The lack of out-of-order message requesting is blocking quite a few things (groups, missing message resolution, sameAs, user invites) so I'd really like to help get this in to pubs ASAP.

cc @dominictarr @christianbundy @mixmix @ahdinosaur @staltz

**Comment by arj03** [comment]
I tried it out a month ago I think and was surprised that it more or less just worked. So +1 from me.

**Comment by cryptix** [comment]
I didn't do intensive testing (resync with hops:1 might be nice weekend exercise) but it hasn't caused trouble for me.

> and not hard coded

you mean enabled by a flag?

**Comment by dominictarr** [comment]
yeah, I think it's good enough. I say go ahead and publish it @mmckegg
