### ISSUE TITLE
[question] multiple identities per device

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-server#609]
Hey, I was hoping someone could tell me if this is crazy or not. Clients, databases, and networks are kind of implicitly coupled in my mind. I was thinking about what if you treat identities, client apps, and networks as separate things.

You could make a separate path for each identity, and keep the database in that folder. So if we start with the convention of `~/.ssb/`, for config, you could instead do `~/.ssb-publicKey/` to store the database for an identity. The idea being that a client app could read all the `.ssb-` prefix folders and let the user choose an identity in the UI.

Also you could present a choice of network, which is identified by the shs caps & sign keys. So maybe have a folder or file in the home directory that is a list of network keys.

And client apps could make another folder for their own config too.

This way you could select a combination of network and identity within a client app. You could potentially choose a database that has been signed with an incompatible shs key, which wouldn't work… and i feel like there are cases where you might accidentally 'leak' things out of the original network. But that could be handled with some logic in the client.

🙏

**Comment by staltz** [comment]
@nichoth Have you seen https://github.com/ssbc/ssb-identities ?
