### ISSUE TITLE
Bug - Hex strings in a message sometimes have leading zeros cut off.

### ISSUE THREAD

**Issue by NiklasKunkel** [ssbc/ssb-server#627]
Running scuttlebot 11.4.1 and 13.2.1 and getting the same issue.

Encountering a weird bug where passing a hex string as an input parameter to a message sometimes leads to the leading zeros cut off. This is strange because it only happens sometimes.

https://imgur.com/rCOp9oE

The input passed for field median0x is: ```0000000000000000000000000000000000000000000000000000005013055420```

In the generated message we see:
```"median0x": 5013055420,```

What's also strange is that the median0x field is now treated as a number rather than a string.

Meanwhile the majority of the time everything works fine.

https://imgur.com/AHlD06X

The input passed for field median0x is:
``` 000000000000000000000000000000000000000000000000016a84d6e0e18000```

In the generated message we see:
``` "median0x": "000000000000000000000000000000000000000000000000016a84d6e0e18000",```

Here we see the leading zeros are not truncated and the field is treated as a string rather than a number. 

Any input on why this is happening?

**Comment by NiklasKunkel** [comment]
Not sure exactly what you're after but maybe this can help. I should note this is a private network I've set up between my own peers.

Here's me creating the message:

`[01/30/19 11:50:47] [V] /home/nkunkel/scuttlebot/bin.js publish --type POLYUSD --version 0.8.9 --median 0.101121 --median0x 0000000000000000000000000000000000000000000000000167410384551000 --time 1548849047 --time0x 000000000000000000000000000000000000000000000000000000005c518f97 --hash 6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c --signature bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c --binance 0.101121 --bittrex 0.101398 --cmc 0.1011176858
[01/30/19 11:50:48] [V] {
  "key": "%w+n5Nd01NrQk9JBR2itVJq5vtH1cIi1mbKnGJa4oZEs=.sha256",
  "value": {
    "previous": "%zt6cCVhPnB0gX4H6YUJcQNOWVFJSKXKvTkWkBJ7s+1Y=.sha256",
    "sequence": 183367,
    "author": "@SoGPH4un5Voz98oAZIbo4hYftc4slv4A+OHXPGCFHpA=.ed25519",
    "timestamp": 1548849047993,
    "hash": "sha256",
    "content": {
      "type": "POLYUSD",
      "version": "0.8.9",
      "median": 0.101121,
      "median0x": 167410384551000,
      "time": 1548849047,
      "time0x": "000000000000000000000000000000000000000000000000000000005c518f97",
      "hash": "6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c",
      "signature": "bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c",
      "binance": 0.101121,
      "bittrex": 0.101398,
      "cmc": 0.1011176858
    },
    "signature": "osCWRxyHOg3wBLt7MsPnpEoZHk2HVL/eiLJ4m/BZlWgDzETd8plqAfVpYMbPrPRP2VzaCWNq3SLAziI/wOLmAw==.sig.ed25519"
  },
  "timestamp": 1548849047993.001
}
`
Here is me querying that same message.

```
nkunkel@Scuttlebot-Peer-A:~/logs$ ~/scuttlebot/bin.js get %w+n5Nd01NrQk9JBR2itVJq5vtH1cIi1mbKnGJa4oZEs=.sha256
{
  "previous": "%zt6cCVhPnB0gX4H6YUJcQNOWVFJSKXKvTkWkBJ7s+1Y=.sha256",
  "sequence": 183367,
  "author": "@SoGPH4un5Voz98oAZIbo4hYftc4slv4A+OHXPGCFHpA=.ed25519",
  "timestamp": 1548849047993,
  "hash": "sha256",
  "content": {
    "type": "POLYUSD",
    "version": "0.8.9",
    "median": 0.101121,
    "median0x": 167410384551000,
    "time": 1548849047,
    "time0x": "000000000000000000000000000000000000000000000000000000005c518f97",
    "hash": "6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c",
    "signature": "bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c",
    "binance": 0.101121,
    "bittrex": 0.101398,
    "cmc": 0.1011176858
  },
  "signature": "osCWRxyHOg3wBLt7MsPnpEoZHk2HVL/eiLJ4m/BZlWgDzETd8plqAfVpYMbPrPRP2VzaCWNq3SLAziI/wOLmAw==.sig.ed25519"
}
```

One thing I have noticed is that the behavior is consistent for the same number. If I submit the exact same median0x argument I can replicate the behavior.

```
nkunkel@Scuttlebot-Peer-A:~/logs$ /home/nkunkel/scuttlebot/bin.js publish --type POLYUSD --version 0.8.9 --median 0.101121 --median0x 0000000000000000000000000000000000000000000000000167410384551000 --time 1548849047 --time0x 000000000000000000000000000000000000000000000000000000005c518f97 --hash 6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c --signature bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c --binance 0.101121 --bittrex 0.101398 --cmc 0.1011176858
{
  "key": "%Sc5U1zU3DcfkpBm1ZgS7GlDQGsgbAZkMFfgTdZ/jyys=.sha256",
  "value": {
    "previous": "%8EqrtIsEI7OEZ/mdHWjTHtFctzmATI8RWrY1knNH2+g=.sha256",
    "sequence": 189247,
    "author": "@SoGPH4un5Voz98oAZIbo4hYftc4slv4A+OHXPGCFHpA=.ed25519",
    "timestamp": 1549078513653,
    "hash": "sha256",
    "content": {
      "type": "POLYUSD",
      "version": "0.8.9",
      "median": 0.101121,
      "median0x": 167410384551000,
      "time": 1548849047,
      "time0x": "000000000000000000000000000000000000000000000000000000005c518f97",
      "hash": "6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c",
      "signature": "bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c",
      "binance": 0.101121,
      "bittrex": 0.101398,
      "cmc": 0.1011176858
    },
    "signature": "WMyVW2ZhN5NSjWqpUPAD4kaCGKf9jxsRJK/1aYqVLiNqRZwNmxmGwat4+g/kfrLzBN3wXG+RCSITnjgNklwsAA==.sig.ed25519"
  },
  "timestamp": 1549078513653.001
}
```

Let me know if there's any other information I can provide.

**Comment by NiklasKunkel** [comment]
@christianbundy edited the above post to provide a lot more information.^

**Comment by christianbundy** [comment]
Oh, that makes sense. We use [minimist](https://github.com/substack/minimist) to parse command-line options, and since you're adding custom options the parser doesn't know whether to parse it as a number or a string. It looks like it's defaulting to string, and the leading zeroes are converting to octal.

```js
// hexadecimal
0x10=== 16

// octal
010 === 8
```

We have a few options:

1. Use the JS API where you can specify that it's a string, not a number.
2. Change your schema to remove the leading zeroes *or* the change the representation -- it may be helpful to know why you need UTF-8 strings of 0x representations.
3. I'd *personally* be keen to merge a PR upgrading us from Minimist to [Yargs](https://github.com/yargs/yargs) or maybe even [Commander](https://github.com/tj/commander.js).

**Comment by dominictarr** [comment]
Oh these are ethereum uint256's I notice you are only using the last few characters in it. Do you really need that full precision? do regular JS numbers not work?

yargs would do the same thing: https://github.com/yargs/yargs/blob/master/docs/tricks.md#numbers

I honestly think minimist is perfect and timeless and does not need to be replaced.

**Comment by dominictarr** [comment]
oh btw, I think if you passed the numbers with a starting `0x` they'd at least be parsed as hex numbers, although they'd still be converted to javascript number (IEEE floats)

**Comment by NiklasKunkel** [comment]
> oh btw, I think if you passed the numbers with a starting 0x they'd at least be parsed as hex numbers, although they'd still be converted to javascript number (IEEE floats)

I actually ran into a lot of problems relating to precision when attempting to do that so to keep things safe and simple I wanted to leave them as a hex string. The message contains a signature composed of signing the hex form median and timestamp with an Ethereum private key. Other peers then see the message and grab the data from them.

> Oh these are ethereum uint256's I notice you are only using the last few characters in it. Do you really need that full precision? do regular JS numbers not work?

We're using a commandline tool called seth to call Ethereum smart contracts and using the hex strings in the messages as uint256 parameters. It expects the inputs to be 32 byte hex strings. I'd like to avoid having the peers that are relaying this data to have to do any transformations on it if possible because the signature verification in the smart contract will fail if the relayers don't transform all the data in the exact same way as the original signer.

It looks like my solutions are:
1. Use the JS API and define these fields as strings
2. Give up on "relayer" peers only consuming data and have them convert the decimal form median and timestamp into hex.

**Comment by dominictarr** [comment]
@NiklasKunkel what are you calling this from? using the JS api would be a natural choice if you are already working in node... there is also clients written in C, go, rust sufficient that they can call to js ssb-server at least.

**Comment by NiklasKunkel** [comment]
I'm writing this is bash because it makes it much more composable with a bunch of other tools we use.

**Comment by dominictarr** [comment]
aha! so this isn't documented anywhere, but I remembered that you can also pipe JSON to stdin and it skips the parsing.

```
echo '{"type": "hex", "hexNumberAsString": "0000000000abc"}' | sbot.publish
```

 via this very old code: https://github.com/ssbc/muxrpcli/blob/master/index.js#L88-L100

**Comment by dominictarr** [comment]
@NiklasKunkel did that JSON pipe tip help?

**Comment by NiklasKunkel** [comment]
Unfortunately no.

`echo '{"type": "POLYUSD", "version": "0.8.9", "median": 0.101121, "median0x": "0000000000000000000000000000000000000000000000000167410384551000", "time": 1548849047, "time0x": 000000000000000000000000000000000000000000000000000000005c518f97, "hash": "6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c", "signature": "bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c", "binance": 0.101121, "bittrex": 0.101398, "cmc": 0.1011176858}' | ~/scuttlebot/bin.js publish
UsageError: Param 0 is required`

**Comment by christianbundy** [comment]
I don't remember where I read this, but I have a weird feeling that you need to `ssb-server publish -` or `ssb-server publish .` or something to get it to read from stdin.

Does that ring a bell? I could've sworn I saw it on a post from @cel I found a few months back.

**Comment by NiklasKunkel** [comment]
Is `ssb-server publish` available via bash?

**Comment by dominictarr** [comment]
@christianbundy you are correct, sir

https://github.com/ssbc/muxrpcli/blob/master/index.js#L42

https://www.youtube.com/watch?v=b3_lVSrPB6w

**Comment by dominictarr** [comment]
@NiklasKunkel do:
`echo JSON | ssb-server publish .`

**Comment by NiklasKunkel** [comment]
I don't seem to be able to run with the alias ssb-server.

I was however able to do it through bin.js by adding the `.`

```
echo '{"type": "POLYUSD", "version": "0.8.9", "median": 0.101121, "median0x": "0000000000000000000000000000000000000000000000000167410384551000", "time": 1548849047, "time0x": "000000000000000000000000000000000000000000000000000000005c518f97", "hash": "6696abd1bbb9f8e6d1abd0dab18c14bd15de3d7459ff4f4dc29441444ffb664c", "signature": "bd9f151b26a751c9453d7c9f269d5dc5e237ab7d8bc9b2fbc30a7609592e8a3f22bdd1a54306498b437e6a9276ff3b19a4fffabffb9ed16f25485c80abf3dbc71c", "binance": 0.101121, "bittrex": 0.101398, "cmc": 0.1011176858}' | ~/scuttlebot/bin.js publish .```

**Comment by dominictarr** [comment]
@NiklasKunkel you'd have had to have done `npm install ssb-server -g` recently (this name depends on some recent refactoring...  mid december)

**Comment by NiklasKunkel** [comment]
I thought I had a recent version (14.0.4), but I'm pulling from the old moniker https://github.com/ssbc/scuttlebot.git so that may be why.

**Comment by dominictarr** [comment]
@NiklasKunkel oh that gets you the correct code, but you won't get the command `ssb-server` unless you install with npm. if you just do `./bin.js` that's fine though.

**Comment by NiklasKunkel** [comment]
Thanks for the help guys @dominictarr @christianbundy I appreciate it. I'll probably be back soon with more stuff XD
