### ISSUE TITLE
plugins/master is always required

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-server#629]
I don't know what it does, but whenever I'm using other plugins I have to add : 

```js
    var Server = require('ssb-server')
      .use(require('ssb-server/plugins/master')) // << non negotiable line
      .use(require('ssb-gossip'))
```

When I don't include it I get mystery errors with ssb-client connections where they're like 
```
{ message: 'method:whoami is not in list of allowed methods',
  name: 'Error',
  stack: 'Error: method:whoami is not in list of allowed methods\n   
```
The result is I feel **stupid**.

Many modules suggest this line is not needed. e.g. https://github.com/ssbc/ssb-replicate

I propose we either document this really well, or back this line in so that it is inside `ssb-server` ..

**Comment by dominictarr** [comment]
@mixmix that isn't a very good response - if something makes you feel stupid,
you should ask why is it like that, then investigate - then you will feel smart.

**Comment by evbogue** [comment]
hey, I also have this question. and I also feel stupid. 

Can we figure out why we need this plugin?

**Comment by mixmix** [comment]
@dominictarr you miss the point of my issue. I know how to fix this... I just have to remember what this one mystery error message is and then add this line.... sometimes it just wastes an hour of my time to remember that.

So yeah there's surface annoyance here. And yes I know how to suck at things and stick with them until I feel smart. I taught people how to do this as a profession, and I taught them by role-modelling it.

The reason I said this made me feel stupid is because I'm being honest about a part of the experience I had AND because I wanted to highlight that if I am feeling even a bit that way, a new person setting out on their first scuttlebutt adventure is probably going to have a worse reaction, like "what the fuck ... I ... fuck this project I'll use [other more centralised ICO funded offering]"

I think we all care about that sort of thing. I understand code get's written in particular ways and evolves. I'm not blaming anyone. I just found a [trip-step](https://www.youtube.com/watch?v=sFNMLqecx-Y) and I'm wondering if we might be wanting to modify our castle so guests don't break their necks exploring

**Comment by dominictarr** [comment]
@mixmix no I feel I do see the point, but there are other points here too. when I read your message - _where you are reacting out of frustration at something about something you do not understand_ I felt that you where putting the onus on me to, for example, explain what that plugin actually does. I my self wasn't sure exactly why it was doing that... so I looked at the code to see. I saw it, and realized that the documentation you were suggesting that it's "always required" is not quite accurate - Wouldn't it be better if the documentation described what it actually did, rather than "include this goblin and don't ask why"? The plugin in question is actually very short, and should only take a minute or two.

I've recently been having a conversation with @pietgeursen about the frustration of code reading. So I wanted to push back to see how you responded @mixmix and, what it looked to you that plugins/master does, etc. I also feel frustrated here by being forced into the situation of "the one who understands"

**Comment by dominictarr** [comment]
btw, I deleted ev's comment. don't really need any pot stiring here, we can handle it

**Comment by mixmix** [comment]
Here's how I read this:
- oh ... there are 2 ways to write plugins, and this is the one that's less obvious to me:
  1. `modules.exports = { name, manifest, init }` - this one's easy to read 
  2. this second way which does a bunch of auto gap filling but I'd have to look up how that works
- `hook`ing of methods?
  - I don't know where this happens or what it does
  - It's not in the main docs, and I've looked for it before
  - I guess it adds listeners / calls which are run before/after/parallel to calls of the method that's hooked? I don't know where I'd look to find out what's hooking things or how to modify existing hooks
- `auth`
  - I don't know where this fits in the stack (so don't know how to go read about it)
  -  `{allow: null, deny: null}` vs `null` ... I presume one of them is a :+1:  and the other :-1: but honestly ... it would be a 50:50 guess... or rather assume the one that is the response to the "is this feedId in the list of those the config set up" means :+1: 

--- 

_I ran these verbally via @dominictarr in a signal message, and he said my guesses were accurate and asked me to write this up so it's clear what is / isn't clear to me. i now feel smart, because I guessed mostly right, but I'm also smart enough to know that relying on mostly right guesses is not really deep understanding!_

**Comment by dominictarr** [comment]
@mixmix thanks! 

> but I'm also smart enough to know that relying on mostly right guesses is not really deep understanding!

I think you are not giving yourself enough credit here! Is there really a hard line between right guesses and understanding? I honestly think I'm operating on the level of good guessing most of the time when I code.

I think the next step is just _confirming your guesses._

**Comment by dominictarr** [comment]
> I guess it adds listeners / calls which are run before/after/parallel to calls of the method that's hooked?
:100: this module: https://github.com/dominictarr/hoox also [discussed in the code reading guide](https://hackmd.io/IM5_tWIfSFuNoe3jtrjrtQ?view#hooking-a-method)
