### ISSUE TITLE
sodium-native/binding issue with the latest electron (4.0.4)

### ISSUE THREAD

**Issue by SyarifZapata** [ssbc/ssb-server#630]
Hello, im trying to build a simple ssb app using ssb and electron. everything worked fine at the begining, but now im getting these error messages when rebuilding the app using `electron-rebuild` command
node v10.15.0
npm v6.4.1
npm install and rebuild didnt help. thanks for your help.

> An unhandled error occurred inside electron-rebuild
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.8.0
> gyp info using node@10.15.1 | linux | x64
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/home/arkad/ssb-electron/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/arkad/ssb-electron/node_modules/ssb-server/node_modules/sodium-native/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/arkad/ssb-electron/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/arkad/.electron-gyp/.node-gyp/4.0.4/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/arkad/.electron-gyp/.node-gyp/4.0.4',
> gyp info spawn args   '-Dnode_gyp_dir=/home/arkad/ssb-electron/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/arkad/.electron-gyp/.node-gyp/4.0.4/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/arkad/ssb-electron/node_modules/ssb-server/node_modules/sodium-native',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory '/home/arkad/ssb-electron/node_modules/ssb-server/node_modules/sodium-native/build'
>   CXX(target) Release/obj.target/sodium/binding.o
> In file included from ../binding.cc:4:0:
> ../libsodium/src/libsodium/include/sodium.h:5:10: fatal error: sodium/version.h: No such file or directory
>  #include "sodium/version.h"
>           ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> sodium.target.mk:117: recipe for target 'Release/obj.target/sodium/binding.o' failed
> make: Leaving directory '/home/arkad/ssb-electron/node_modules/ssb-server/node_modules/sodium-native/build'
> make: *** [Release/obj.target/sodium/binding.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/home/arkad/ssb-electron/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.15.0-45-generic
> gyp ERR! command "/home/arkad/.nvm/versions/node/v10.15.1/bin/node" "/home/arkad/ssb-electron/node_modules/.bin/node-gyp" "rebuild" "--target=4.0.4" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
> gyp ERR! cwd /home/arkad/ssb-electron/node_modules/ssb-server/node_modules/sodium-native
> gyp ERR! node -v v10.15.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> 
> Failed with exit code: 1
> 
> 
>

**Comment by christianbundy** [comment]
Hey @SyarifZapata, thanks for opening a new issue. I was under the impression that you were using a pre-existing Electron client, which is why I recommended `npm run rebuild`. Since you're running your own client (:tada:) you'll likely need something like [electron-rebuild](https://github.com/electron/electron-rebuild).

In Patchwork/Patchbay we do it like [this](https://github.com/ssbc/patchwork/blob/bb6ea7736458cc3a8af61ba2954c057c6e21dbdd/package.json#L13), but the gist is that you need to run `npm rebuild` with a few flags so that it's rebuilding for your Electron's Node ABI, **not** the Node ABI from the host system. Does that make sense?

**Comment by SyarifZapata** [comment]
Thanks @christianbundy, it works now.
