### ISSUE TITLE
Plugins not working?

### ISSUE THREAD

**Issue by luandro** [ssbc/ssb-server#636]
Upgraded from `scuttlebot` to `ssb-server` and now I get errors regarding the plugins. Here's what I have:
```
const sbot = require('ssb-server')
    .use(require('ssb-server/plugins/master'))
    .use(require('ssb-server/plugins/gossip'))
    .use(require('ssb-server/plugins/replicate'))
```
The `gossip` and `replicate` plugins throw a `Cannot find module` error.

**Comment by christianbundy** [comment]
Hey @luandro 

Yeah, these have been refactored into their own modules in 14.0.0 -- see here: https://github.com/ssbc/ssb-server/blob/master/bin.js#L45-L61

**Comment by luandro** [comment]
Thanks @christianbundy   :+1:
