### ISSUE TITLE
after updating can no longer call commands on sbot/ssb-server without an error

### ISSUE THREAD

**Issue by frankiebee** [ssbc/ssb-server#647]
after updating can no longer call comands on sbot/ssb-server without an error
error: `Cannot read property 'apply' of undefined`

node -v
v10.11.0
npm -v
6.4.1

repro:
- start patchbay or ssb-server
- open new tab in terminal 
- `> ssb-server --help` || `sbot --help`

**Comment by frankiebee** [comment]
oooh was help removed?

**Comment by frankiebee** [comment]
on that note to how do i install plugins now?

**Comment by frankiebee** [comment]
new node version also means node_modules in .ssb needed to be rebubilt 
sense a rebuild failed  
ive just decided to reinstall plugins 
but well i'm hitting a idk how to do that anymore sense it seems thats no longer an option from sbot

**Comment by frankiebee** [comment]
semi solution / frankie is insane 😅 

i removed node modules and turned off all my plugins and am not starting sbot outside of patchbay 

ux issue: always takes me about an hour or 2 to update sbot i think last time i just nuked everything and resynced my whole feed but at that time i knew how to install plugins

this most likely isnt a problem with sbot and is more around node but i'm sure some of this could be avoided

**Comment by dominictarr** [comment]
to rebuild plugins: `cd ~/.ssb && npm rebuild`

`sbot plugins.install <plugin_name>` still works.
but in my opinion, we should probably remove npm from sbot... you can also install a plugin manually by doing `cd ~/.ssb && npm install <plugin>` and then editing `~/.ssb/config` so that `"plugins": {"<module_name>": true},`

**Comment by frankiebee** [comment]
so @dominictarr rebuild failed and sbot dosent seem to know `plugins.install`

i get:
```
Command not found: plugins.install
Cannot read property 'apply' of undefined
```

**Comment by dominictarr** [comment]
weird... what version of ssb-server did you install? I'm using 14.1.7
oh what it might be: if you are running patchbay's sbot, they might not have plugins.
check `~/.ssb/manifest.json` and see if it has a plugins section.

**Comment by frankiebee** [comment]
> oh what it might be: if you are running patchbay's sbot, they might not have plugins.
yeah okay running my outside of patchbay works for plugins 

but `--help` is no longer an option in the update?

**Comment by frankiebee** [comment]
sbot version
"19.1.0"

**Comment by dominictarr** [comment]
Hmm, oh that is the ssb-db version, not the ssb-server version... oh now I see what happened. We moved the code that was in ssb-server into ssb-db so now it reports that version!

that should probably the versions of all the plugins, anyway!

**Comment by dominictarr** [comment]
@frankiebee how did you do install ssb-server, did you do `npm install ssb-server -g` or is it the one that's inside of patchbay?

**Comment by dominictarr** [comment]
or did you git clone it then install?

**Comment by frankiebee** [comment]
`npm install ssb-server -g`

**Comment by frankiebee** [comment]
should i be `git clone`ing it?

**Comment by dominictarr** [comment]
my hunch is that you are hitting the sbot that is bundled inside of patchbay, [that doesn't use plugins](https://github.com/ssbc/patchbay/blob/master/server.js#L8-L14) which would explain why you are not getting any.

**Comment by dominictarr** [comment]
we really should have a better way to detect what plugins are running.

**Comment by frankiebee** [comment]
when i'm only using my sbot and not running patch bay i still dont get the --help so i dont know my options here

**Comment by dominictarr** [comment]
issue for reinstating help text and version numbers: https://github.com/ssbc/ssb-server/issues/648
