### ISSUE TITLE
ssb-server version returns ssb-db version instead

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-server#649]
🤷‍♂️🤷‍♀️😕

**Comment by mmckegg** [comment]
<img width="680" alt="Screen Shot 2019-03-15 at 1 22 04 PM" src="https://user-images.githubusercontent.com/66834/54399895-59f37400-4725-11e9-8ac0-10f6c034618e.png">

**Comment by dominictarr** [comment]
this was a side effect of the recent refactor. see https://github.com/ssbc/ssb-server/issues/648
