### ISSUE TITLE
Npm install fails when building from source in Docker Ubuntu container

### ISSUE THREAD

**Issue by NiklasKunkel** [ssbc/ssb-server#654]
Trying to install scuttlebot inside of an Ubuntu Docker container fails.

Ubuntu 18.04.2 LTS
npm v6.7.0
node v11.13.0

```
git clone https://github.com/ssbc/scuttlebot.git /home/scuttlebot
cd /home/scuttlebot
git checkout 2d99b57c60e4d9d4013a0bdbe61347f093b651f7
npm install
npm ERR! Cannot read property 'match' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-04T21_27_32_096Z-debug.log
```

Debug logfile:
> 17 silly saveTree +-- ssb-ref@2.13.9
> 17 silly saveTree `-- ssb-replicate@1.2.1
> 17 silly saveTree   +-- observ-debounce@1.1.1
> 17 silly saveTree   | `-- observ@0.2.0
> 17 silly saveTree   `-- pull-next@1.0.1
> 18 verbose stack TypeError: Cannot read property 'match' of undefined
> 18 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
> 18 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
> 18 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
> 18 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 18 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
> 18 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
> 18 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 18 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
> 18 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 18 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 18 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
> 18 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
> 18 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
> 18 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
> 18 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
> 18 verbose stack     at processImmediate (internal/timers.js:443:21)
> 19 verbose cwd /home/scuttlebot
> 20 verbose Linux 4.9.125-linuxkit
> 21 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
> 22 verbose node v11.13.0
> 23 verbose npm  v6.7.0
> 24 error Cannot read property 'match' of undefined
> 25 verbose exit [ 1, true ]

**Comment by NiklasKunkel** [comment]
Deleting `npm-shrinkwrap.json` fixed this issue.

**Comment by arj03** [comment]
I had the same issue. How hard can it be to build a decent package manager?

**Comment by christianbundy** [comment]
@dominictarr I've noticed that this happens often after you commit a "fix shrinkwrap" change. In the future could you check the Travis output to make sure that it's working before pushing to `master`?
