### ISSUE TITLE
the local plugin doesn't respect `caps.shs`

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-server#657]
See more info : %EvCzVh6zl7s0nqSsNXxCJ9iHy2F27dTw8Cf/u2e56rg=.sha256

basically if you have two peers on the same wifi with different `caps.shs` they are added to each others peer tables (but they do not replicate with each other). The results in a confusing experience at the moment as "localPeers" includes peers you shouldn't even be talking to

**Comment by staltz** [comment]
I'm interested in hearing what was @dominictarr's idea for this, since it concerns "gossip" plugin and I have a few thoughts around this, not only for wi-fi broadcast, but also for Bluetooth.

**Comment by staltz** [comment]
[ssb-lan](https://github.com/staltz/ssb-lan) supports distinguishing LAN peers with different caps.shs, so I'd say this issue is done.
