### ISSUE TITLE
ssb.webcookies.pub

### ISSUE THREAD

**Issue by kravietz** [ssbc/ssb-server#661]
Please add [ssb.webcookies.pub](http://ssb.webcookies.pub) to the list of publicly available pubs. The server is also available over Yggdrasil as [y.webcookies.pub](http://y.webcookies.pub/)

**Comment by dominictarr** [comment]
it's a wiki I think you can just edit it yourself?

**Comment by kravietz** [comment]
Ah right, thanks!
