### ISSUE TITLE
Error while installing ssb-npm with sodium-native

### ISSUE THREAD

**Issue by buoyantair** [ssbc/ssb-server#676]
I have been trying to install ssb-npm & then ssb-git and I have some errors popping up...
This is on my MacOS Mojave machine (10.14.5 (18F203)), I gave my logs below

While trying to checkout the command `sbot plugins`:
```
$ sbot plugins
error loading sodium bindings: Cannot find module 'sodium-native'
Require stack:
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/bindings.js
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-keys/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/defaults.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/inject.js
- /usr/local/lib/node_modules/ssb-server/bin.js
falling back to javascript version.
install|uninstall|enable|disable
```

When trying to start sbot(ssb-server):
```
$ sbot start
error loading sodium bindings: Cannot find module 'sodium-native'
Require stack:
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/bindings.js
- /usr/local/lib/node_modules/ssb-server/node_modules/chloride/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-keys/index.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/defaults.js
- /usr/local/lib/node_modules/ssb-server/node_modules/ssb-config/inject.js
- /usr/local/lib/node_modules/ssb-server/bin.js
falling back to javascript version.
ssb-server 15.0.1 /Users/alice.kile/.ssb logging.level:notice
my key ID: REDACTED :P 
ssb-friends: stream legacy api used
^C************************************************ ()
```

and then, even during the installation of scuttlebot, I have this massive error which is most likely coming from node-gyp not being able to compile well on my mac...

**Comment by dominictarr** [comment]
that looks like it's actually working, just it didn't manage to install sodium native.
what does the npm error look like?

**Comment by jedahan** [comment]
I had to use node 10 instead of 12 for libsodium to install. I wonder if we need the error message at all if we fall back to JavaScript anyway

**Comment by eldilibra** [comment]
I experienced this same issue. Switching to Node v10.16.0 cleared it up.

@dominictarr would the npm error log still be useful to you?

**Comment by staltz** [comment]
sodium-native is an `optionalDependencies` so I think you could try `npm install --no-optional` and then it won't even install sodium-native.

**Comment by eldilibra** [comment]
Ah, is it included as a performance enhancement?

**Comment by staltz** [comment]
Yes
