### ISSUE TITLE
Unable to sync new data

### ISSUE THREAD

**Issue by noffle** [ssbc/ssb-server#679]
I recently noticed that my ssb client (patchfoo) is no longer showing new data from my network. I've tried updating ssb-server and also reinstalling it, but the issue remains. I also tried using patchbay instead, which also didn't sync down any new content.

Any suggestions for things I might look for to debug?

**Comment by arj03** [comment]
Strange. Can you see if you are connecting to pubs in the terminal?

In patchbay there is a /network tab that will show you how many new messages you got and who you are connected to.

**Comment by noffle** [comment]
@arj03 I don't see connections to pubs in my terminal. I don't think I ever have though.

Loading the patchbay /network tab brought up this /errors tab:

```
Cannot read property 'sync' of undefined
TypeError: Cannot read property 'sync' of undefined
    at HTMLAnchorElement.ev-click (/tmp/.mount_patchbyyCeyI/resources/app.asar/app/page/network.js:29:33)
```

**Comment by arj03** [comment]
You can try settings logging to info in .ssb/config and see if anything good comes up:

```
  "logging": {
    "level": "info"
  },
```

Any idea what might have caused this? Did you do anything special?

**Comment by noffle** [comment]
Thanks @arj03. I'm not seeing any new output with logging level set to info.

Not sure what caused it! I did run some code using `secret-stack` recently, which hopefully didn't mess with my ssb config or anything?

**Comment by noffle** [comment]
I looked at patchfoo's status tab and see

```json
{
  "progress": {
    "indexes": {
      "start": 69190638,
      "current": 664558727,
      "target": 691906398
    }
  },
  "sync": {
    "since": 691906398,
    "plugins": {
      "last": 691906398,
      "keys": 691906398,
      "clock": 691906398,
      "time": 691906398,
      "feed": 691906398,
      "contacts2": 691906398,
      "query": 691906398,
      "links2": 691906398,
      "private-C3iYh_12s": 418429688,
      "backlinks-C3iYh_12s": 691906398
    },
    "sync": false
  },
  "gossip": {},
  "ooo": {}
}
```

`sync: false` and `gossip: {}` looked suspicious to me.

**Comment by arj03** [comment]
Try disabling plugins in ~/.ssb/config and see if one of them is causing this.

Also there should be a gossip section in there. If all are false then it won't connect to anything until you manually initiate a connection.

**Comment by dominictarr** [comment]
@noffle I don't understand the patchbay error. Looking at the line referenced in the patchbay code doesn't make sense...

`sync: false` means your database views are not up to date. They are all correct except
`      "private-C3iYh_12s": 418429688,`
try `rm ~/.ssb/flume/private-C3iYh_12s/*` and restart

Is this a problem with sbot receiving the messages or just the client?

What is the most recent message received? `sbot createLogStream --limit 1 --reverse` do you see that message in the client (maybe it's not a public message...) I'm not sure exactly what patchbay uses to display the feed these days...

what versions are you using of everything?

**Comment by noffle** [comment]
@dominictarr

I wiped the dir you suggested, and watched it regenerate itself back up all of the way. Now status is:

```json
{
  "progress": {
    "indexes": {
      "start": 691906398,
      "current": 691906398,
      "target": 691906398
    }
  },
  "sync": {
    "since": 691906398,
    "plugins": {
      "last": 691906398,
      "keys": 691906398,
      "clock": 691906398,
      "time": 691906398,
      "feed": 691906398,
      "contacts2": 691906398,
      "query": 691906398,
      "links2": 691906398,
      "private-C3iYh_12s": 691906398,
      "backlinks-C3iYh_12s": 691906398
    },
    "sync": true
  },
  "gossip": {},
  "ooo": {}
}
```

My last recv'd message is from 1562630022164, which is a message *I* posted 3 days ago. Key is `%jWb3BmSauf7xdp1u3Jz8Ec0u/eqaJxyr2DZxxtPclW8=.sha256`.

I'm running `ssb-server@15.0.2`.

**Comment by arj03** [comment]
Strange. Wonder if you forked your feed somehow. The latest message I have from you is %ASQWTucPoFdC2g9xp3E5d5Kzmk5eQ/moUQSQIlbjafE=.sha256.

**Comment by dominictarr** [comment]
okay the most suspucious thing then is that you don't have any peers. do you have a non-empty gossip.json?
it's possible to switch off replication in your config... what does your config look like?

**Comment by noffle** [comment]
`gossip.json` is 445886 bytes.

`config`:

```json
{
  "plugins": {
    "ssb-private": true,
    "ssb-fulltext": true,
    "patchfoo": true,
    "ssb-ooo": false,
    "ssb-inbox": false,
    "ssb-backlinks": true,
    "ssb-dns": false,
    "ssb-npm-registry": true,
    "ssb-gitindex": false,
    "git-ssb-web": false,
    "ssb-about": false,
    "ssb-links": false,
    "ssb-exec": true,
    "ssb-identities": true
  },
  "blobs": {
    "max": 10000000
  },
  "replicate": {
    "legacy": false
  },
  "friends": {
    "hops": 2
  },
  "gossip": {
    "global": false
  },
  "logging": {
    "level": "info"
  }
}
```

**Comment by arj03** [comment]
That gossip.global = false should be the cause :)

**Comment by noffle** [comment]
@arj03 I tried that -- it doesn't seem to change anything. I've had that setting for many months /wo issue.

**Comment by christianbundy** [comment]
@noffle 

Any luck syncing with Patchwork or Oasis? Neither uses ssb-server so they might have slightly different versions of the relevant plugins.

**Comment by dominictarr** [comment]
@noffle well, `gossip.global = false` is _meant_ to stop you connecting to remote peers.
It will still connect to local peers, addresses in `seeds = []`

since we can see from the status output that you don't have any peers... please try changing that, if it works we can figure out why it might have worked until recently

**Comment by noffle** [comment]
Weird, setting `gossip.global` to `false` fixed it. I swear I tried this earlier /wo result. Not sure why this used to work!
