### ISSUE TITLE
Not storing messages sent in reply to createHistoryStream

### ISSUE THREAD

**Issue by bl0x** [ssbc/ssb-server#696]
The server does not store the messages sent in reply to

`createHistoryStream`

but also does not print any error messages.

`ssb-server log`

only prints the messages of the server's own feed.

How can I see more debug output from ssb-server?

I've tried

`ssb-server start --logging.level=info`

but that did not increase the verbosity.

**Comment by dominictarr** [comment]
I'm not sure what you are trying to do? who is calling `createHistoryStream`? If the server called createHistoryStream another instance, and messages were received back but if they were invalid, they will be ignored. That could be what's happening... hard to say though because I don't really understand what you are trying to do exactly. Can you describe in more detail or post some code?

**Comment by bl0x** [comment]
Thanks for getting back to me.

Backstory: I'm working on an alternative implementation of the ssb protocol in ANSI C. Following the protocol guide closely. The main aim is to be able to run a pub server based on this development.
Code is not (yet) public.

I'm running both the server / client on a separate net with its own shs and sign caps.

I've found that `ssb-validate:checkInvalidCheap()` does not validate my messages.
It also does not complain (on the terminal) about this fact, so I investigated using printouts.

For reference, this is the first message I'm sending:

With keys:

```
{
  "key": "%0vFZzedNK4f9TDIFf7+0vMaa2YrgKLMorLy/LjAp6zA=.sha256",
  "value": {
    "previous": null,
    "author": "@hZScgcftJgGIFGtZzSHfkNhBAnzfp4iUIOvLlaxT3Dk=.ed25519",
    "sequence": 1,
    "timestamp": 1570680433079,
    "hash": "sha256",
    "content": {
      "type": "about",
      "about": "@hZScgcftJgGIFGtZzSHfkNhBAnzfp4iUIOvLlaxT3Dk=.ed25519",
      "name": "test-pub (kp2pc253)"
    },
    "signature": "mDDrMvTd2AbXyoZyXCsRtpRiNVFgSmz9tfMLkT/TiwFtpOkVipE40XUcfzUKiZuveIzZExTjm8yYkhzrXUGOAA==.sig.ed25519"
  },
  "timestamp": 1570680433079
}
```

Without keys:
```
{
    "previous": null,
    "author": "@hZScgcftJgGIFGtZzSHfkNhBAnzfp4iUIOvLlaxT3Dk=.ed25519",
    "sequence": 1,
    "timestamp": 1570680433079,
    "hash": "sha256",
    "content": {
      "type": "about",
      "about": "@hZScgcftJgGIFGtZzSHfkNhBAnzfp4iUIOvLlaxT3Dk=.ed25519",
      "name": "test-pub (kp2pc253)"
    }
}
```

Either I'm sending the messages with keys, then I get the error:
```
checkInvalid: err =  Error: invalid message: must have author
```
with the reason, that no "key" / "value" keys are expected.

Or, I'm sending the messages without keys, then I get this error:
```
checkInvalid: err =  Error: message must have keys in allowed order
```
In this case the error happens, because the keys AND signature are not included in the message.
Inside `isValidOrder()`:
```
signed =  true
keys (6) =  [ 'previous', 'author', 'sequence', 'timestamp', 'hash', 'content' ]
```

What am I doing wrong here?

Edit: I've forgotten to append the signature when sending without keys. Now the signature verification does not pass. I'll investigate further.

Do you have a text file with test messages one can use to verify the message encoding / decoding and signing / verification?

**Comment by dominictarr** [comment]
> Backstory: I'm working on an alternative implementation of the ssb protocol in ANSI C.

Wow, that's great! very excited to hear this. I do recommend just making the unfinished code public though. btw, @clehner has also been working on a C implementation, but it's all on ssb accessed via [git-ssb](https://github.com/clehner/git-ssb) ;) I think there is much value in parallel implementations but I just want to make sure you know it exists.

Yes there is test data: https://github.com/ssbc/ssb-validate/tree/master/test/data
contains a set of valid messages that should be accepted and also invalid messages that should be rejected.

There is also the rather more precise spec that @AljoschaMeyer wrote over here: https://spec.scuttlebutt.nz/introduction.html

**Comment by bl0x** [comment]
Thanks for the information.
I'll have a look and see that those messages validate.
Also the UTF8/16 conversion in the spec was a little bit unexpected.
Great fun ahead!

**Comment by bl0x** [comment]
Turns out, the main problem was that I told the other client (patchwork) to use a sign cap, while I was not signing the messages with one. Information on how that sign cap is used is also missing in all the documentation I could find (besides code in ssb-keys & ssb-validate).

Replication with patchwork works now, so I'll probably release the code soon.

Regarding validation: The test_messages.json I could check now as valid/invalid as expected, but this did not force me to look into the UTF16 encoding. Missing some test messages for this?

**Comment by dominictarr** [comment]
oh hmm, the last message in `test_messages.json` that tests is `"type": "euros"` then thousands of euros characters, because the max length is measured as utf8 code points, so if you only use utf8 you can have a message length approaching 32k, instead of 8k. that test data doesn't include what the hashes should be... but it should.

**Comment by bl0x** [comment]
From my side, this can be closed.
