### ISSUE TITLE
CLI gets stuck at `ssb-friends`

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-server#715]
```
.ssb-foo nick$ ssb_appname="ssb-foo" ssb-server start
ssb-server 15.2.0 /Users/nick/.ssb-foo logging.level:notice
my key ID: cldncCeFL3QN1XtRT3E/ZtBpW+FQJ5s+IqTiJFrbRGs=.ed25519
ssb-friends: stream legacy api used
************************************************** ()
```
This is when starting sbot as a cli command. It gets stuck at that point. Followed the instructions [here](https://josiahwitt.com/2018/07/08/scuttlebutt-intro-test-playground.html) thus far (general info about setting up a test network)

**Comment by D3191** [comment]
This is normal, all you need to do is run ssb-server from a detachable session like [screens ](https://linuxize.com/post/how-to-use-linux-screen/)or [tmux](https://wiki.archlinux.org/index.php/Tmux).  

I use screens personally, its really easy all you do is: 

1.`sudo apt install screen`

2. `screen`

run your command to start ssb-server 

then press Ctrl a + d to detach the session.

**Comment by nichoth** [comment]
hmm that's interesting. I haven't done this yet because I'm on mac & it looks like the instructions are for linux. i wonder what difference it makes using a program like those

**Comment by nichoth** [comment]
I see now, it looks like the text output from `ssb-server start` just stops at an awkward place. If you try an sbot command in a separate terminal it does work.
