### ISSUE TITLE
sbot whoami, Error: Could not connect to ssb-server localhost:8008

### ISSUE THREAD

**Issue by mrweiss** [ssbc/ssb-server#721]
Hi,
I was running a pub some time ago using ssb-server, I've wiped the VPS and tried to set everything up again, but I am running into issues with the newer version of ssb-server - it's the same VPS/setup as before, fresh install - would anyone see this issue before? Thank you!

`
Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.1.3.el7.x86_64
      Architecture: x86-64
`

Following https://scuttlebot.io/docs/config/create-a-pub.html setting the hostname to one that matches the A record for the server's IP address.

> yum install npm
> yum install screen
> npm install -g ssb-server
> screen -S scuttlebutt
> sh ~/run-sbotserver.sh
ssb-server 15.2.0 /root/.ssb logging.level:notice
my key ID: Ql8EuHS3ode0FPbZqp882xva5jc/tjDxfBRI4yQ0088=.ed25519
ssb-friends: stream legacy api used
************************************************** ()

**ctrl+a d**

> sbot whoami
Error: Could not connect to ssb-server localhost:8008
Use the "start" command to start it.
Use --verbose option to see full error

**Comment by Vertux** [comment]
What is the output of `lsof -PiTCP -sTCP:LISTEN|grep 8008` ?

**Comment by mrweiss** [comment]
![image](https://user-images.githubusercontent.com/22911545/84500491-91482c00-acac-11ea-8ed7-11c43e7394d4.png)

**Comment by mrweiss** [comment]
ok to close, moved away from ssbc
