### ISSUE TITLE
Node is now on version 14

### ISSUE THREAD

**Issue by egils-consulting** [ssbc/ssb-server#730]
Is it hard to make it work out of the box with v14?

**Comment by egils-consulting** [comment]
I'm using it wih node14 and it seems to work just fine. I suggest you update the installation instructions.

**Comment by arj03** [comment]
A PR is very welcome :)

**Comment by egils-consulting** [comment]
I did this to install:
sudo npm install --global sodium-native (this installs v3 that works with the new node)
git clone --depth 1 https://github.com/ssbc/ssb-server.git
cd ssb-server
npm install -g ssb-server

I now get this error, but I don't know if it affects the functionallity. 
ssb-git and ssb-git-web works fine at least and now I'm trying to get patchfoo to work.

**Comment by arj03** [comment]
Thats this one: https://github.com/dominictarr/chloride/pull/16.
